window:
  padding:
    x: 8
    y: 8
  decorations: none
  opacity: 0.99
  startup_mode: Maximized
  dynamic_title: true
  decorations_theme_variant: None

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: CaskaydiaCove Nerd Font Mono
    style: Regular
  bold:
    family: CaskaydiaCove Nerd Font Mono
    style: Bold
  italic:
    family: CaskaydiaCove Nerd Font Mono
    style: Italic
  bold_italic:
    family: CaskaydiaCove Nerd Font Mono
    style: Bold Italic
  size: 11.0

draw_bold_text_with_bright_colors: false

# Start flavours
# Base16 Purpledream 256 - alacritty color config
# malet
colors:
  # Default colors
  primary:
    background: '0x100510'
    foreground: '0xddd0dd'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x100510'
    cursor: '0xddd0dd'

  # Normal colors
  normal:
    black:   '0x100510'
    red:     '0xff1d0d'
    green:   '0x14cc64'
    yellow:  '0xf000a0'
    blue:    '0x00a0f0'
    magenta: '0xb000d0'
    cyan:    '0x0075b0'
    white:   '0xddd0dd'

  # Bright colors
  bright:
    black:   '0x605060'
    red:     '0xff1d0d'
    green:   '0x14cc64'
    yellow:  '0xf000a0'
    blue:    '0x00a0f0'
    magenta: '0xb000d0'
    cyan:    '0x0075b0'
    white:   '0xfff0ff'

  indexed_colors:
    - { index: 16, color: '0xccae14' }
    - { index: 17, color: '0x6a2a3c' }
    - { index: 18, color: '0x302030' }
    - { index: 19, color: '0x403040' }
    - { index: 20, color: '0xbbb0bb' }
    - { index: 21, color: '0xeee0ee' }
# End flavours

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: On
  vi_mode_style: Block
  blink_interval: 750
  blink_timeout: 5
  unfocused_hollow: true

live_config_reload: true
working_directory: None
