#!/bin/bash

function nodejs() {
  curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
  apt-get install -y nodejs
}

function docker() {
  curl -fsSL https://get.docker.com | bash -
  usermod -aG docker "${USER}"
}

echo "➜ Installing \"${1}\"..."

case $1 in
  nodejs) nodejs;;
  docker) docker;;
  *)
    echo "✘ Not eligible install script for \"${1}\""
    exit 1
    ;;
esac

echo "✔ \"${1}\" successfully installed!"
